events { 
    worker_connections 1024; 
}

http { 
    upstream pool_dinamico {
        # O DNS interno do Docker vai resolver esse nome para N IPs automaticamente!
        server wordpress_app;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        
        root /usr/share/nginx/html;
        index index.php;

        location / {
            add_header X-Upstream $upstream_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
            
            # Apontando para o nosso pool dinâmico
            proxy_pass http://pool_dinamico;
        }
    }
}